-- Show products with their categories

SELECT
    p.product_name,
    p.brand,
    c.category_name,
    p.price
FROM products p
JOIN categories c
ON p.category_id = c.category_id;


-- Show customers with their orders

SELECT
    c.customer_name,
    c.city,
    o.order_id,
    o.order_date,
    o.total_amount
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id;


-- Show order payment details

SELECT
    o.order_id,
    o.order_date,
    p.payment_method,
    p.payment_status,
    p.transaction_amount
FROM orders o
JOIN payments p
ON o.order_id = p.order_id;


-- Show top 10 highest value orders

SELECT
    c.customer_name,
    o.order_id,
    o.total_amount
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
ORDER BY o.total_amount DESC
LIMIT 10;


-- Show product inventory details

SELECT
    p.product_name,
    c.category_name,
    p.stock_quantity,
    p.price
FROM products p
JOIN categories c
ON p.category_id = c.category_id
ORDER BY p.stock_quantity DESC;


-- Show complete order details with customer and payment information

SELECT
    c.customer_name,
    c.city,
    o.order_id,
    o.order_date,
    p.payment_method,
    p.payment_status,
    p.transaction_amount
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
JOIN payments p
ON o.order_id = p.order_id;


-- Show products sold in each order

SELECT
    oi.order_id,
    p.product_name,
    oi.quantity,
    oi.unit_price,
    oi.final_price
FROM order_items oi
JOIN products p
ON oi.product_id = p.product_id;


-- Show top 10 most expensive products

SELECT
    product_name,
    brand,
    price
FROM products
ORDER BY price DESC
LIMIT 10;


-- Find top customers by total order amount

SELECT
    c.customer_name,
    ROUND(SUM(o.total_amount),2) AS total_spent
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
GROUP BY c.customer_name
ORDER BY total_spent DESC
LIMIT 10;


-- Calculate revenue generated by each city

SELECT
    c.city,
    ROUND(SUM(p.transaction_amount),2) AS revenue
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
JOIN payments p
ON o.order_id = p.order_id
WHERE p.payment_status = 'Success'
GROUP BY c.city
ORDER BY revenue DESC;


-- Calculate revenue by category

SELECT
    c.category_name,
    ROUND(SUM(oi.final_price),2) AS revenue
FROM categories c
JOIN products p
ON c.category_id = p.category_id
JOIN order_items oi
ON p.product_id = oi.product_id
GROUP BY c.category_name
ORDER BY revenue DESC;
