-- Find top 10 customers by total spending

SELECT
    c.customer_id,
    c.customer_name,
    ROUND(SUM(o.total_amount), 2) AS total_spent
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
GROUP BY
    c.customer_id,
    c.customer_name
ORDER BY total_spent DESC
LIMIT 10;


-- Find customers with the highest number of orders

SELECT
    c.customer_name,
    COUNT(o.order_id) AS total_orders
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
GROUP BY c.customer_name
ORDER BY total_orders DESC
LIMIT 10;


-- Find top selling products

SELECT
    p.product_name,
    SUM(oi.quantity) AS quantity_sold
FROM products p
JOIN order_items oi
ON p.product_id = oi.product_id
GROUP BY p.product_name
ORDER BY quantity_sold DESC
LIMIT 10;


-- Find products generating highest revenue

SELECT
    p.product_name,
    ROUND(SUM(oi.final_price), 2) AS revenue
FROM products p
JOIN order_items oi
ON p.product_id = oi.product_id
GROUP BY p.product_name
ORDER BY revenue DESC
LIMIT 10;


-- Calculate revenue generated by each category

SELECT
    c.category_name,
    ROUND(SUM(oi.final_price), 2) AS revenue
FROM categories c
JOIN products p
ON c.category_id = p.category_id
JOIN order_items oi
ON p.product_id = oi.product_id
GROUP BY c.category_name
ORDER BY revenue DESC;


-- Calculate average rating by category

SELECT
    c.category_name,
    ROUND(AVG(p.rating), 2) AS average_rating
FROM categories c
JOIN products p
ON c.category_id = p.category_id
GROUP BY c.category_name
ORDER BY average_rating DESC;


-- Calculate payment success percentage

SELECT
    payment_status,
    COUNT(*) AS total_transactions
FROM payments
GROUP BY payment_status;